# 台股每日爬蟲教學

In [14]:
import requests
from io import StringIO
import pandas as pd
import numpy as np

datestr = '20180131'

# 下載股價
r = requests.post('https://www.twse.com.tw/exchangeReport/MI_INDEX?response=csv&date=' + datestr + '&type=ALL')

# 整理資料，變成表格
df = pd.read_csv(StringIO(r.text.replace("=", "")), 
            header=["證券代號" in l for l in r.text.split("\n")].index(True)-1)

# 整理一些字串：

df.apply(lambda s: pd.to_numeric(s.astype(str).str.replace(",", "").replace("+", "1").replace("-", "-1"), errors='coerce'))
df

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比,Unnamed: 16
0,0050,元大台灣50,"4,251,739","1,176","359,040,915",84.40,85.00,84.15,84.65,+,0.10,84.60,21,84.65,80,0.00,NaN
1,0051,元大中型100,"7,500",3,"243,040",32.39,32.39,32.39,32.39,+,0.09,32.39,43,32.50,5,0.00,NaN
2,0052,富邦科技,"4,001",5,"229,706",57.35,57.60,57.30,57.40,+,0.05,57.35,1,57.90,1,0.00,NaN
3,0053,元大電子,1,1,37,--,--,--,--,,0.00,37.09,50,37.35,1,0.00,NaN
4,0054,元大台商50,"2,001",3,"48,904",24.44,24.44,24.44,24.44,-,0.05,24.41,50,24.64,8,0.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13718,9944,新麗,"31,013",28,"612,197",19.75,19.75,19.70,19.70,+,0.05,19.70,3,19.75,10,50.51,NaN
13719,9945,潤泰新,"3,736,138","1,927","124,164,872",33.00,33.70,32.65,33.45,+,0.40,33.45,15,33.50,52,7.55,NaN
13720,9946,三發地產,"188,743",83,"2,429,334",12.80,13.00,12.80,13.00,-,0.05,12.90,3,13.00,4,13.98,NaN
13721,9955,佳龍,"69,012",49,"1,037,730",14.80,15.15,14.80,15.00,+,0.20,14.95,7,15.00,1,0.00,NaN
13722,9958,世紀鋼,"7,951,033","3,588","337,437,513",39.10,43.65,39.10,43.65,+,3.95,43.60,186,43.65,1,136.41,NaN

In [15]:
df.head()

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比,Unnamed: 16
0,0050,元大台灣50,"4,251,739","1,176","359,040,915",84.40,85.00,84.15,84.65,+,0.10,84.60,21,84.65,80,0.00,NaN
1,0051,元大中型100,"7,500",3,"243,040",32.39,32.39,32.39,32.39,+,0.09,32.39,43,32.50,5,0.00,NaN
2,0052,富邦科技,"4,001",5,"229,706",57.35,57.60,57.30,57.40,+,0.05,57.35,1,57.90,1,0.00,NaN
3,0053,元大電子,1,1,37,--,--,--,--,,0.00,37.09,50,37.35,1,0.00,NaN
4,0054,元大台商50,"2,001",3,"48,904",24.44,24.44,24.44,24.44,-,0.05,24.41,50,24.64,8,0.00,NaN